model:
  params:
    simple_shell: true
    enable_tiles: false
    enable_rim: false
    enable_honeycomb: false
export:
  output_dir: "./out/papierkorb/shell"
  basename: papierkorb_shell
  scad: true
  stl: true
  png:
    enabled: true
    imgsize: [1200, 900]
    viewall: true
    view: edges
